### ISSUE TITLE
Chokes on IE filters

### ISSUE THREAD

**Issue by pistolero** [klen/python-scss#21]
SCSS is unable to parse following constructs:

```
div { filter: alpha(opacity=85); }
```

or

```
div { filter:progid:DXImageTransform.Microsoft.Alpha(opacity=60); }
```

**Comment by vgarvardt** [comment]
same for me
exception on

``` css
#menu {
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#f858ef', endColorstr='#ffe413', GradientType=1);
}
```
